### ISSUE TITLE
我试图复现这个论文，请问requirement环境版本间有冲突怎么解决

### ISSUE THREAD

**Issue by czx1220** [yfchen1994/poisoning_membership#2]
我试图复现这个论文，请问requirement环境版本间有冲突怎么解决
![0181e003aedd7f8e7e889ce5d1d563d](https://github.com/yfchen1994/poisoning_membership/assets/164853445/cc02db36-7ce6-4634-afc1-6770c5471deb)

**Comment by yfchen1994** [comment]
Thanks for your interest in our work! 👋 

I've updated the `requirements.txt` file. Please kindly pull the changes and try again. Sorry for the inconvenience caused.

**Comment by czx1220** [comment]
thanks！

**Comment by czx1220** [comment]
你好，我有两个疑问：
1. 代码运行是获取数据集和模型后就立刻把他删除了吗，为什么我在对应的路径没找到任何东西
![image](https://github.com/yfchen1994/poisoning_membership/assets/164853445/6baff5ff-8d1c-4128-aee5-8c43cef8864e)
2. 关于这段代码，这里model刚获取，就del删除掉了，意义是什么呢？
![image](https://github.com/yfchen1994/poisoning_membership/assets/164853445/a4ee5a7e-713c-454c-84ba-adf3c91ef7d0)

**Comment by yfchen1994** [comment]
Hi,

Regarding Question 1, could you please provide additional details about the results obtained after running the code? It would be helpful to know the current sub-directories and any logging information available. Having more specific information will assist in identifying and resolving the issue quickly.

During the evaluation stage, the code reads the poisoning data and the poisoned model stored on the disk and then performs the evaluation. If the code displays the evaluation results, it indicates that the dataset and model should be located in their respective directories.

---

As for Question 2, before the ``del`` command is executed, the function ``get_poisoned_model()`` is called to generate the poisoned model and save it to the disk.

Subsequently, the ``del`` command is used to remove the poisoned model from the current session. This step is necessary to explicitly release the GPU memory occupied by the poisoned model. Without this explicit release, the memory used by the poisoned model may not be freed, leading to GPU memory leakage when generating additional poisoned models.

**Comment by czx1220** [comment]
明白了，谢谢！我发现clean_label_attack训练的很慢，是不是没有放到gpu上运行？我没有看到gpu上面运行的代码

**Comment by yfchen1994** [comment]
Hi,

You may monitor the GPU usage during the code execution. If you find the code is not executed on GPU, try to choose the GPU device by setting the argument ``--device_no``. An alternative approach is to modify [Line 21 of poisoning_attack.py](https://github.com/yfchen1994/poisoning_membership/blob/a036d734460faab6e4f21ed6aa699fd2426b6a18/poisoning_attack.py#L21).

Hope the above suggestions are helpful to you! 🤗
